# docker-compose.yml
name: "hku-proxy-project" 

services:
  hku-proxy:
    build: .
    container_name: hku_proxy_service
    env_file:
      - .env
    ports:
      - "${PROXY_PORT:-8000}:8000"
    restart: unless-stopped
    volumes:
      # This maps the './traces' folder on your Mac 
      # to the '/app/traces' folder inside the container.
      - ./traces:/app/traces
